version: "3.9"
services:
  book:
    build: ./booking_service
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - ./bookingapp:/opt/bookingapp

  core:
    build: ./core_service
    ports:
      - "8081:8081"
    depends_on:
      - price
      - book
      - trip
      - redis
    volumes:
      - ./coreapp:/opt/coreapp
  price:
    build: ./pricing_service
    ports:
      - "8082:8082"
    depends_on:
      - redis
    volumes:
      - ./priceapp:/opt/priceapp
  trip:
    build: ./trip_service
    ports:
      - "8083:8083"
    depends_on:
      - redis
    volumes:
      - ./tripapp:/opt/tripapp
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"